# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'To_Do' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for To_Do
    pod 'SwiftLint'

  target 'To_DoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'To_DoUITests' do
    # Pods for testing
  end

end
